version: "3.8"

networks:
  transnet:
    driver: bridge
    name: transnet

# volumes:
#   localdrive:
#     driver: local
#     name: localdrive
#     driver_opts:
#       device: ${PWD}
#       type: none
#       o: bind
# this is broken for file changes, they don't seem to showup correctly for a modified file
# no idea why this is the case, new files and deleted files so showup, but a modified file 
# always shows the original file
#    volumes:
#      - ${PWD}:/web

services:
  nest:
    container_name: nest
    build: requirements/nest
    networks:
      - transnet
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}:/backend
    init: true

  react:
    container_name: react
    build: requirements/react
    networks:
      - transnet
    ports:
      - "5173:5173"
    volumes:
      - ${PWD}:/app
    init: true

  postgres:
    container_name: postgres
    build: requirements/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=testdb
    networks:
      - transnet
    volumes:
      - ${PWD}:/database
    init: true
