networks:
  transnet:
    driver: bridge
    name: transnet

volumes:
  database:
  avatars:
  frontend:

services:
  nest:
    build:
      context: ./
      dockerfile: requirements/nest/prod.Dockerfile
    restart: always
    volumes:
      - avatars:/avatars
    networks:
      - transnet
    env_file:
      - .env
    ports:
     - "3000:3000"

  react:
    build:
        context: ./
        dockerfile: requirements/react/prod.Dockerfile
    volumes:
      - frontend:/app/dist
    env_file:
      - .env

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USR}
      - POSTGRES_PASSWORD=${DATABASE_PWD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - transnet

  nginx:
    build:
      context: requirements/nginx
      dockerfile: prod.Dockerfile
    restart: always
    networks:
      - transnet
    env_file:
      - .env
    volumes:
      - frontend:/var/www/html
    environment:
      - NGINX_PORT=8080
    ports:
      - "8080:8080"