version: "3.8"

networks:
  transnet:
    driver: bridge
    name: transnet

services:
  nest:
    container_name: nest
    build: requirements/nest
    networks:
      - transnet
    ports:
      - "3000:3000"
      - "5555:5555" #for prisma studio
    volumes:
      - ./:/backend
    env_file:
      - env/.nestjs.env
    init: true

  react:
    container_name: react
    build: requirements/react
    networks:
      - transnet
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
    env_file:
      - env/.react.env
    init: true

  postgres:
    container_name: postgres
    build: requirements/postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PWD}
    networks:
      - transnet
    volumes:
      - ./:/database
    init: true

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./requirements/nginx/templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks:
      - transnet
    depends_on:
      - react
